// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertTurns implements pgx.CopyFromSource.
type iteratorForInsertTurns struct {
	rows                 []InsertTurnsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertTurns) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertTurns) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ReportID,
		r.rows[0].Idx,
		r.rows[0].Role,
		r.rows[0].Content,
	}, nil
}

func (r iteratorForInsertTurns) Err() error {
	return nil
}

func (q *Queries) InsertTurns(ctx context.Context, arg []InsertTurnsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"turns"}, []string{"report_id", "idx", "role", "content"}, &iteratorForInsertTurns{rows: arg})
}
