// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Report struct {
	ID            int64
	ShareUrl      string
	Provider      string
	Model         string
	ParserVersion int32
	Status        string
	SubmittedAt   pgtype.Timestamptz
}

type Turn struct {
	ReportID int64
	Idx      int32
	Role     string
	Content  string
}
