// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const insertReport = `-- name: InsertReport :one
INSERT INTO reports (share_url, provider, model, parser_version, status)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (share_url) DO NOTHING
RETURNING id
`

type InsertReportParams struct {
	ShareUrl      string
	Provider      string
	Model         string
	ParserVersion int32
	Status        string
}

func (q *Queries) InsertReport(ctx context.Context, arg InsertReportParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertReport,
		arg.ShareUrl,
		arg.Provider,
		arg.Model,
		arg.ParserVersion,
		arg.Status,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

type InsertTurnsParams struct {
	ReportID int64
	Idx      int32
	Role     string
	Content  string
}
