- targets:
    - edge-health-wildcard.guardianintelligence.org
    - guardianintelligence.org
    - api.guardianintelligence.org
    - alerta.guardianintelligence.org
    - dashboard.guardianintelligence.org
    - grafana.guardianintelligence.org
    - harbor.guardianintelligence.org
    - keycloak.guardianintelligence.org
    - s3.guardianintelligence.org
  labels:
    guardian_record_type: A
    guardian_stage: root
    guardian_surface: edge
