apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tenant-guardian-release-beta
resources:
  - ../../../../../components/openbao-github-integration-secrets
labels:
  - includeSelectors: false
    pairs:
      guardian.dev/component: release
      guardian.dev/stage: beta
      guardian.dev/tenant-id: gi-release-beta
