load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "journaltest",
    testonly = True,
    srcs = ["journaltest.go"],
    importpath = "github.com/guardian-intelligence/guardian/src/services/mythrad/journal/journaltest",
    visibility = ["//src/services/mythrad:__subpackages__"],
    deps = ["//src/services/mythrad/journal"],
)
