apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alertmanager/base
  - blackbox-exporter/base
  - clickhouse/base
  - gatus/base
  - grafana/base
  - kube-state-metrics/base
  - otel-collector/base
  - vmalert/base
