apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-state-metrics.yaml
images:
  - name: registry.guardian.internal/kube-state-metrics
    newName: registry.guardian.internal/kube-state-metrics
    newTag: bootstrap
