apiVersion: openbao.guardian.dev/v1alpha1
kind: OpenBaoPolicy
metadata:
  name: cert-manager-openbao-api-issuer
spec:
  name: guardian-cert-manager-openbao-api-issuer
  rules: |
    path "pki/openbao-api/sign/openbao-api" {
      capabilities = ["update"]
    }
  deletionPolicy: Retain
