apiVersion: openbao.guardian.dev/v1alpha1
kind: OpenBaoPolicy
metadata:
  name: external-dns
spec:
  name: guardian-external-dns
  rules: |
    path "kv/data/guardian/guardian-mgmt/tenant-guardian/dns/external-dns" {
      capabilities = ["read"]
    }

    path "kv/metadata/guardian/guardian-mgmt/tenant-guardian/dns/external-dns" {
      capabilities = ["read"]
    }
  deletionPolicy: Retain
