apiVersion: openbao.guardian.dev/v1alpha1
kind: OpenBaoPolicy
metadata:
  name: ops-controller
spec:
  name: guardian-openbao-ops-controller
  rules: |
    path "sys/policies/acl/guardian-*" {
      capabilities = ["create", "read", "update", "delete"]
    }

    path "sys/auth" {
      capabilities = ["read", "sudo"]
    }

    path "sys/auth/kubernetes" {
      capabilities = ["create", "read", "update", "delete", "sudo"]
    }

    path "sys/auth/kubernetes/tune" {
      capabilities = ["read", "update", "sudo"]
    }

    path "auth/kubernetes/config" {
      capabilities = ["read", "update"]
    }

    path "auth/kubernetes/role/guardian-*" {
      capabilities = ["create", "read", "update", "delete"]
    }

    path "sys/mounts" {
      capabilities = ["read", "sudo"]
    }

    path "sys/mounts/kv" {
      capabilities = ["create", "read", "update", "delete", "sudo"]
    }

    path "sys/mounts/kv/tune" {
      capabilities = ["read", "update", "sudo"]
    }
  deletionPolicy: Retain
