apiVersion: apps.cozystack.io/v1alpha1
kind: Tenant
metadata:
  name: dev
  namespace: tenant-guardiancommercial-platform
  labels:
    app.kubernetes.io/part-of: guardian
    guardian.dev/product: platform
    guardian.dev/stage: dev
spec:
  host: dev.gi.org
  etcd: false
  ingress: false
  monitoring: false
  seaweedfs: false
