apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alertmanager.yaml
images:
  - name: registry.guardian.internal/alertmanager
    newName: registry.guardian.internal/alertmanager
    newTag: bootstrap
