// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: canaries.sql

package paymentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachCanaryOrder = `-- name: AttachCanaryOrder :exec
UPDATE payment_canary_runs SET order_id = $2 WHERE id = $1
`

type AttachCanaryOrderParams struct {
	ID      string      `db:"id" json:"id"`
	OrderID pgtype.Text `db:"order_id" json:"order_id"`
}

func (q *Queries) AttachCanaryOrder(ctx context.Context, arg AttachCanaryOrderParams) error {
	_, err := q.db.Exec(ctx, attachCanaryOrder, arg.ID, arg.OrderID)
	return err
}

const completeCanaryRun = `-- name: CompleteCanaryRun :one
UPDATE payment_canary_runs
SET status = $2,
    failure_class = $3,
    completed_at = now()
WHERE id = $1 AND status = 'running'
RETURNING id, order_id, trace_id, lane, status, failure_class, started_at, completed_at
`

type CompleteCanaryRunParams struct {
	ID           string      `db:"id" json:"id"`
	Status       string      `db:"status" json:"status"`
	FailureClass pgtype.Text `db:"failure_class" json:"failure_class"`
}

func (q *Queries) CompleteCanaryRun(ctx context.Context, arg CompleteCanaryRunParams) (PaymentCanaryRun, error) {
	row := q.db.QueryRow(ctx, completeCanaryRun, arg.ID, arg.Status, arg.FailureClass)
	var i PaymentCanaryRun
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.TraceID,
		&i.Lane,
		&i.Status,
		&i.FailureClass,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const countCanaryFailures = `-- name: CountCanaryFailures :one
SELECT count(*)::bigint
FROM payment_canary_runs
WHERE status = 'failed'
  AND started_at > now() - $1::interval
`

func (q *Queries) CountCanaryFailures(ctx context.Context, intervalWindow pgtype.Interval) (int64, error) {
	row := q.db.QueryRow(ctx, countCanaryFailures, intervalWindow)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getCanaryRun = `-- name: GetCanaryRun :one
SELECT id, order_id, trace_id, lane, status, failure_class, started_at, completed_at FROM payment_canary_runs WHERE id = $1
`

func (q *Queries) GetCanaryRun(ctx context.Context, id string) (PaymentCanaryRun, error) {
	row := q.db.QueryRow(ctx, getCanaryRun, id)
	var i PaymentCanaryRun
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.TraceID,
		&i.Lane,
		&i.Status,
		&i.FailureClass,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const latestCanaryRuns = `-- name: LatestCanaryRuns :many
SELECT DISTINCT ON (lane) id, order_id, trace_id, lane, status, failure_class, started_at, completed_at
FROM payment_canary_runs
ORDER BY lane, started_at DESC
`

func (q *Queries) LatestCanaryRuns(ctx context.Context) ([]PaymentCanaryRun, error) {
	rows, err := q.db.Query(ctx, latestCanaryRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentCanaryRun{}
	for rows.Next() {
		var i PaymentCanaryRun
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.TraceID,
			&i.Lane,
			&i.Status,
			&i.FailureClass,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startCanaryRun = `-- name: StartCanaryRun :one
INSERT INTO payment_canary_runs (id, trace_id, lane, status)
VALUES ($1, $2, $3, 'running')
RETURNING id, order_id, trace_id, lane, status, failure_class, started_at, completed_at
`

type StartCanaryRunParams struct {
	ID      string `db:"id" json:"id"`
	TraceID string `db:"trace_id" json:"trace_id"`
	Lane    string `db:"lane" json:"lane"`
}

func (q *Queries) StartCanaryRun(ctx context.Context, arg StartCanaryRunParams) (PaymentCanaryRun, error) {
	row := q.db.QueryRow(ctx, startCanaryRun, arg.ID, arg.TraceID, arg.Lane)
	var i PaymentCanaryRun
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.TraceID,
		&i.Lane,
		&i.Status,
		&i.FailureClass,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}
