// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package paymentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimProviderEvent = `-- name: ClaimProviderEvent :one
UPDATE provider_events
SET processing_started_at = now(),
    attempt_count = attempt_count + 1
WHERE (provider_account_id, event_id) = (
    SELECT provider_account_id, event_id
    FROM provider_events
    WHERE processed_at IS NULL
      AND (
        processing_started_at IS NULL
        OR processing_started_at < now() - interval '2 minutes'
      )
    ORDER BY received_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING provider_account_id, event_id, event_type, object_id, api_version, livemode, payload, received_at, processing_started_at, processed_at, attempt_count, last_error_class
`

func (q *Queries) ClaimProviderEvent(ctx context.Context) (ProviderEvent, error) {
	row := q.db.QueryRow(ctx, claimProviderEvent)
	var i ProviderEvent
	err := row.Scan(
		&i.ProviderAccountID,
		&i.EventID,
		&i.EventType,
		&i.ObjectID,
		&i.ApiVersion,
		&i.Livemode,
		&i.Payload,
		&i.ReceivedAt,
		&i.ProcessingStartedAt,
		&i.ProcessedAt,
		&i.AttemptCount,
		&i.LastErrorClass,
	)
	return i, err
}

const countPendingProviderEvents = `-- name: CountPendingProviderEvents :one
SELECT count(*)::bigint FROM provider_events WHERE processed_at IS NULL
`

func (q *Queries) CountPendingProviderEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingProviderEvents)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUnmatchedBalanceTransactions = `-- name: CountUnmatchedBalanceTransactions :one
SELECT count(*)::bigint
FROM provider_balance_transactions
WHERE (order_id IS NULL OR ledger_projected_at IS NULL)
  AND first_seen_at < now() - interval '15 minutes'
`

func (q *Queries) CountUnmatchedBalanceTransactions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnmatchedBalanceTransactions)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertProviderEvent = `-- name: InsertProviderEvent :one
INSERT INTO provider_events (
    provider_account_id, event_id, event_type, object_id, api_version,
    livemode, payload
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (provider_account_id, event_id) DO NOTHING
RETURNING provider_account_id, event_id, event_type, object_id, api_version, livemode, payload, received_at, processing_started_at, processed_at, attempt_count, last_error_class
`

type InsertProviderEventParams struct {
	ProviderAccountID string      `db:"provider_account_id" json:"provider_account_id"`
	EventID           string      `db:"event_id" json:"event_id"`
	EventType         string      `db:"event_type" json:"event_type"`
	ObjectID          pgtype.Text `db:"object_id" json:"object_id"`
	ApiVersion        pgtype.Text `db:"api_version" json:"api_version"`
	Livemode          bool        `db:"livemode" json:"livemode"`
	Payload           []byte      `db:"payload" json:"payload"`
}

func (q *Queries) InsertProviderEvent(ctx context.Context, arg InsertProviderEventParams) (ProviderEvent, error) {
	row := q.db.QueryRow(ctx, insertProviderEvent,
		arg.ProviderAccountID,
		arg.EventID,
		arg.EventType,
		arg.ObjectID,
		arg.ApiVersion,
		arg.Livemode,
		arg.Payload,
	)
	var i ProviderEvent
	err := row.Scan(
		&i.ProviderAccountID,
		&i.EventID,
		&i.EventType,
		&i.ObjectID,
		&i.ApiVersion,
		&i.Livemode,
		&i.Payload,
		&i.ReceivedAt,
		&i.ProcessingStartedAt,
		&i.ProcessedAt,
		&i.AttemptCount,
		&i.LastErrorClass,
	)
	return i, err
}

const markProviderEventProcessed = `-- name: MarkProviderEventProcessed :exec
UPDATE provider_events
SET processed_at = now(),
    last_error_class = NULL
WHERE provider_account_id = $1 AND event_id = $2
`

type MarkProviderEventProcessedParams struct {
	ProviderAccountID string `db:"provider_account_id" json:"provider_account_id"`
	EventID           string `db:"event_id" json:"event_id"`
}

func (q *Queries) MarkProviderEventProcessed(ctx context.Context, arg MarkProviderEventProcessedParams) error {
	_, err := q.db.Exec(ctx, markProviderEventProcessed, arg.ProviderAccountID, arg.EventID)
	return err
}

const markProviderEventRetryable = `-- name: MarkProviderEventRetryable :exec
UPDATE provider_events
SET processing_started_at = NULL,
    last_error_class = $3
WHERE provider_account_id = $1 AND event_id = $2
`

type MarkProviderEventRetryableParams struct {
	ProviderAccountID string      `db:"provider_account_id" json:"provider_account_id"`
	EventID           string      `db:"event_id" json:"event_id"`
	LastErrorClass    pgtype.Text `db:"last_error_class" json:"last_error_class"`
}

func (q *Queries) MarkProviderEventRetryable(ctx context.Context, arg MarkProviderEventRetryableParams) error {
	_, err := q.db.Exec(ctx, markProviderEventRetryable, arg.ProviderAccountID, arg.EventID, arg.LastErrorClass)
	return err
}

const oldestPendingProviderEventAgeSeconds = `-- name: OldestPendingProviderEventAgeSeconds :one
SELECT COALESCE(EXTRACT(EPOCH FROM now() - min(received_at)), 0)::bigint
FROM provider_events
WHERE processed_at IS NULL
`

func (q *Queries) OldestPendingProviderEventAgeSeconds(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, oldestPendingProviderEventAgeSeconds)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertBalanceTransaction = `-- name: UpsertBalanceTransaction :one
INSERT INTO provider_balance_transactions (
    provider_account_id, balance_transaction_id, source_id,
    reporting_category, transaction_type, currency, gross_cents, fee_cents,
    net_cents, available_on, provider_created_at, raw, order_id,
    ledger_projected_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
ON CONFLICT (provider_account_id, balance_transaction_id) DO UPDATE
SET source_id = EXCLUDED.source_id,
    reporting_category = EXCLUDED.reporting_category,
    transaction_type = EXCLUDED.transaction_type,
    currency = EXCLUDED.currency,
    gross_cents = EXCLUDED.gross_cents,
    fee_cents = EXCLUDED.fee_cents,
    net_cents = EXCLUDED.net_cents,
    available_on = EXCLUDED.available_on,
    raw = EXCLUDED.raw,
    order_id = COALESCE(
        provider_balance_transactions.order_id,
        EXCLUDED.order_id
    ),
    ledger_projected_at = COALESCE(
        provider_balance_transactions.ledger_projected_at,
        EXCLUDED.ledger_projected_at
    ),
    last_seen_at = now()
RETURNING provider_account_id, balance_transaction_id, source_id, reporting_category, transaction_type, currency, gross_cents, fee_cents, net_cents, available_on, provider_created_at, raw, order_id, ledger_projected_at, first_seen_at, last_seen_at
`

type UpsertBalanceTransactionParams struct {
	ProviderAccountID    string             `db:"provider_account_id" json:"provider_account_id"`
	BalanceTransactionID string             `db:"balance_transaction_id" json:"balance_transaction_id"`
	SourceID             pgtype.Text        `db:"source_id" json:"source_id"`
	ReportingCategory    string             `db:"reporting_category" json:"reporting_category"`
	TransactionType      string             `db:"transaction_type" json:"transaction_type"`
	Currency             string             `db:"currency" json:"currency"`
	GrossCents           int64              `db:"gross_cents" json:"gross_cents"`
	FeeCents             int64              `db:"fee_cents" json:"fee_cents"`
	NetCents             int64              `db:"net_cents" json:"net_cents"`
	AvailableOn          pgtype.Timestamptz `db:"available_on" json:"available_on"`
	ProviderCreatedAt    pgtype.Timestamptz `db:"provider_created_at" json:"provider_created_at"`
	Raw                  []byte             `db:"raw" json:"raw"`
	OrderID              pgtype.Text        `db:"order_id" json:"order_id"`
	LedgerProjectedAt    pgtype.Timestamptz `db:"ledger_projected_at" json:"ledger_projected_at"`
}

func (q *Queries) UpsertBalanceTransaction(ctx context.Context, arg UpsertBalanceTransactionParams) (ProviderBalanceTransaction, error) {
	row := q.db.QueryRow(ctx, upsertBalanceTransaction,
		arg.ProviderAccountID,
		arg.BalanceTransactionID,
		arg.SourceID,
		arg.ReportingCategory,
		arg.TransactionType,
		arg.Currency,
		arg.GrossCents,
		arg.FeeCents,
		arg.NetCents,
		arg.AvailableOn,
		arg.ProviderCreatedAt,
		arg.Raw,
		arg.OrderID,
		arg.LedgerProjectedAt,
	)
	var i ProviderBalanceTransaction
	err := row.Scan(
		&i.ProviderAccountID,
		&i.BalanceTransactionID,
		&i.SourceID,
		&i.ReportingCategory,
		&i.TransactionType,
		&i.Currency,
		&i.GrossCents,
		&i.FeeCents,
		&i.NetCents,
		&i.AvailableOn,
		&i.ProviderCreatedAt,
		&i.Raw,
		&i.OrderID,
		&i.LedgerProjectedAt,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}
