// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package paymentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countJournalIncomplete = `-- name: CountJournalIncomplete :one
SELECT count(*)::bigint
FROM ledger_commands
WHERE intent_journaled_at IS NULL
   OR tigerbeetle_accepted_at IS NULL
   OR outcome_journaled_at IS NULL
`

func (q *Queries) CountJournalIncomplete(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countJournalIncomplete)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const ensureLedgerAccount = `-- name: EnsureLedgerAccount :one
INSERT INTO ledger_accounts (
    registry_key, account_id, ledger, code, flags,
    user_data_128, user_data_64, user_data_32
) VALUES ($1, $2, 2, $3, $4, $5, $6, $7)
ON CONFLICT (registry_key) DO UPDATE
SET registry_key = EXCLUDED.registry_key
RETURNING registry_key, account_id, ledger, code, flags, user_data_128, user_data_64, user_data_32, created_at, accepted_at
`

type EnsureLedgerAccountParams struct {
	RegistryKey string `db:"registry_key" json:"registry_key"`
	AccountID   string `db:"account_id" json:"account_id"`
	Code        int32  `db:"code" json:"code"`
	Flags       int32  `db:"flags" json:"flags"`
	UserData128 string `db:"user_data_128" json:"user_data_128"`
	UserData64  int64  `db:"user_data_64" json:"user_data_64"`
	UserData32  int32  `db:"user_data_32" json:"user_data_32"`
}

func (q *Queries) EnsureLedgerAccount(ctx context.Context, arg EnsureLedgerAccountParams) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, ensureLedgerAccount,
		arg.RegistryKey,
		arg.AccountID,
		arg.Code,
		arg.Flags,
		arg.UserData128,
		arg.UserData64,
		arg.UserData32,
	)
	var i LedgerAccount
	err := row.Scan(
		&i.RegistryKey,
		&i.AccountID,
		&i.Ledger,
		&i.Code,
		&i.Flags,
		&i.UserData128,
		&i.UserData64,
		&i.UserData32,
		&i.CreatedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const ensureLedgerCommand = `-- name: EnsureLedgerCommand :one
INSERT INTO ledger_commands (
    command_key, order_id, correlation_id, transfer_capture_id,
    transfer_fee_id, transfer_grant_id
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (command_key) DO UPDATE
SET command_key = EXCLUDED.command_key
RETURNING command_key, order_id, correlation_id, transfer_capture_id, transfer_fee_id, transfer_grant_id, payload, intent_journaled_at, tigerbeetle_accepted_at, outcome_journaled_at, result, created_at
`

type EnsureLedgerCommandParams struct {
	CommandKey        string      `db:"command_key" json:"command_key"`
	OrderID           string      `db:"order_id" json:"order_id"`
	CorrelationID     string      `db:"correlation_id" json:"correlation_id"`
	TransferCaptureID string      `db:"transfer_capture_id" json:"transfer_capture_id"`
	TransferFeeID     pgtype.Text `db:"transfer_fee_id" json:"transfer_fee_id"`
	TransferGrantID   string      `db:"transfer_grant_id" json:"transfer_grant_id"`
}

func (q *Queries) EnsureLedgerCommand(ctx context.Context, arg EnsureLedgerCommandParams) (LedgerCommand, error) {
	row := q.db.QueryRow(ctx, ensureLedgerCommand,
		arg.CommandKey,
		arg.OrderID,
		arg.CorrelationID,
		arg.TransferCaptureID,
		arg.TransferFeeID,
		arg.TransferGrantID,
	)
	var i LedgerCommand
	err := row.Scan(
		&i.CommandKey,
		&i.OrderID,
		&i.CorrelationID,
		&i.TransferCaptureID,
		&i.TransferFeeID,
		&i.TransferGrantID,
		&i.Payload,
		&i.IntentJournaledAt,
		&i.TigerbeetleAcceptedAt,
		&i.OutcomeJournaledAt,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const markLedgerAccountAccepted = `-- name: MarkLedgerAccountAccepted :exec
UPDATE ledger_accounts
SET accepted_at = COALESCE(accepted_at, now())
WHERE registry_key = $1
`

func (q *Queries) MarkLedgerAccountAccepted(ctx context.Context, registryKey string) error {
	_, err := q.db.Exec(ctx, markLedgerAccountAccepted, registryKey)
	return err
}

const markLedgerCommandAccepted = `-- name: MarkLedgerCommandAccepted :exec
UPDATE ledger_commands
SET tigerbeetle_accepted_at = COALESCE(tigerbeetle_accepted_at, now()),
    result = $2
WHERE command_key = $1
`

type MarkLedgerCommandAcceptedParams struct {
	CommandKey string `db:"command_key" json:"command_key"`
	Result     []byte `db:"result" json:"result"`
}

func (q *Queries) MarkLedgerCommandAccepted(ctx context.Context, arg MarkLedgerCommandAcceptedParams) error {
	_, err := q.db.Exec(ctx, markLedgerCommandAccepted, arg.CommandKey, arg.Result)
	return err
}

const markLedgerCommandIntentJournaled = `-- name: MarkLedgerCommandIntentJournaled :exec
UPDATE ledger_commands
SET intent_journaled_at = COALESCE(intent_journaled_at, now())
WHERE command_key = $1
`

func (q *Queries) MarkLedgerCommandIntentJournaled(ctx context.Context, commandKey string) error {
	_, err := q.db.Exec(ctx, markLedgerCommandIntentJournaled, commandKey)
	return err
}

const markLedgerCommandOutcomeJournaled = `-- name: MarkLedgerCommandOutcomeJournaled :exec
UPDATE ledger_commands
SET outcome_journaled_at = COALESCE(outcome_journaled_at, now())
WHERE command_key = $1
`

func (q *Queries) MarkLedgerCommandOutcomeJournaled(ctx context.Context, commandKey string) error {
	_, err := q.db.Exec(ctx, markLedgerCommandOutcomeJournaled, commandKey)
	return err
}

const setLedgerCommandPayload = `-- name: SetLedgerCommandPayload :exec
UPDATE ledger_commands SET payload = $2 WHERE command_key = $1
`

type SetLedgerCommandPayloadParams struct {
	CommandKey string `db:"command_key" json:"command_key"`
	Payload    []byte `db:"payload" json:"payload"`
}

func (q *Queries) SetLedgerCommandPayload(ctx context.Context, arg SetLedgerCommandPayloadParams) error {
	_, err := q.db.Exec(ctx, setLedgerCommandPayload, arg.CommandKey, arg.Payload)
	return err
}
