// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package paymentdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LedgerAccount struct {
	RegistryKey string             `db:"registry_key" json:"registry_key"`
	AccountID   string             `db:"account_id" json:"account_id"`
	Ledger      int32              `db:"ledger" json:"ledger"`
	Code        int32              `db:"code" json:"code"`
	Flags       int32              `db:"flags" json:"flags"`
	UserData128 string             `db:"user_data_128" json:"user_data_128"`
	UserData64  int64              `db:"user_data_64" json:"user_data_64"`
	UserData32  int32              `db:"user_data_32" json:"user_data_32"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	AcceptedAt  pgtype.Timestamptz `db:"accepted_at" json:"accepted_at"`
}

type LedgerCommand struct {
	CommandKey            string             `db:"command_key" json:"command_key"`
	OrderID               string             `db:"order_id" json:"order_id"`
	CorrelationID         string             `db:"correlation_id" json:"correlation_id"`
	TransferCaptureID     string             `db:"transfer_capture_id" json:"transfer_capture_id"`
	TransferFeeID         pgtype.Text        `db:"transfer_fee_id" json:"transfer_fee_id"`
	TransferGrantID       string             `db:"transfer_grant_id" json:"transfer_grant_id"`
	Payload               []byte             `db:"payload" json:"payload"`
	IntentJournaledAt     pgtype.Timestamptz `db:"intent_journaled_at" json:"intent_journaled_at"`
	TigerbeetleAcceptedAt pgtype.Timestamptz `db:"tigerbeetle_accepted_at" json:"tigerbeetle_accepted_at"`
	OutcomeJournaledAt    pgtype.Timestamptz `db:"outcome_journaled_at" json:"outcome_journaled_at"`
	Result                []byte             `db:"result" json:"result"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PaymentCanaryRun struct {
	ID           string             `db:"id" json:"id"`
	OrderID      pgtype.Text        `db:"order_id" json:"order_id"`
	TraceID      string             `db:"trace_id" json:"trace_id"`
	Lane         string             `db:"lane" json:"lane"`
	Status       string             `db:"status" json:"status"`
	FailureClass pgtype.Text        `db:"failure_class" json:"failure_class"`
	StartedAt    pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt  pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

type PaymentOrder struct {
	ID                         string             `db:"id" json:"id"`
	TenantID                   string             `db:"tenant_id" json:"tenant_id"`
	Provider                   string             `db:"provider" json:"provider"`
	ProviderAccountID          string             `db:"provider_account_id" json:"provider_account_id"`
	Currency                   string             `db:"currency" json:"currency"`
	AmountCents                int64              `db:"amount_cents" json:"amount_cents"`
	Synthetic                  bool               `db:"synthetic" json:"synthetic"`
	Status                     string             `db:"status" json:"status"`
	TraceID                    string             `db:"trace_id" json:"trace_id"`
	StripeCheckoutSessionID    pgtype.Text        `db:"stripe_checkout_session_id" json:"stripe_checkout_session_id"`
	StripePaymentIntentID      pgtype.Text        `db:"stripe_payment_intent_id" json:"stripe_payment_intent_id"`
	StripeChargeID             pgtype.Text        `db:"stripe_charge_id" json:"stripe_charge_id"`
	StripeBalanceTransactionID pgtype.Text        `db:"stripe_balance_transaction_id" json:"stripe_balance_transaction_id"`
	FailureClass               pgtype.Text        `db:"failure_class" json:"failure_class"`
	CreatedAt                  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	PaidAt                     pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	LedgerPostedAt             pgtype.Timestamptz `db:"ledger_posted_at" json:"ledger_posted_at"`
}

type PaymentReconcilerState struct {
	ProviderAccountID      string             `db:"provider_account_id" json:"provider_account_id"`
	BalanceCursorCreatedAt pgtype.Timestamptz `db:"balance_cursor_created_at" json:"balance_cursor_created_at"`
	LastSuccessAt          pgtype.Timestamptz `db:"last_success_at" json:"last_success_at"`
	LastErrorClass         pgtype.Text        `db:"last_error_class" json:"last_error_class"`
}

type ProviderBalanceTransaction struct {
	ProviderAccountID    string             `db:"provider_account_id" json:"provider_account_id"`
	BalanceTransactionID string             `db:"balance_transaction_id" json:"balance_transaction_id"`
	SourceID             pgtype.Text        `db:"source_id" json:"source_id"`
	ReportingCategory    string             `db:"reporting_category" json:"reporting_category"`
	TransactionType      string             `db:"transaction_type" json:"transaction_type"`
	Currency             string             `db:"currency" json:"currency"`
	GrossCents           int64              `db:"gross_cents" json:"gross_cents"`
	FeeCents             int64              `db:"fee_cents" json:"fee_cents"`
	NetCents             int64              `db:"net_cents" json:"net_cents"`
	AvailableOn          pgtype.Timestamptz `db:"available_on" json:"available_on"`
	ProviderCreatedAt    pgtype.Timestamptz `db:"provider_created_at" json:"provider_created_at"`
	Raw                  []byte             `db:"raw" json:"raw"`
	OrderID              pgtype.Text        `db:"order_id" json:"order_id"`
	LedgerProjectedAt    pgtype.Timestamptz `db:"ledger_projected_at" json:"ledger_projected_at"`
	FirstSeenAt          pgtype.Timestamptz `db:"first_seen_at" json:"first_seen_at"`
	LastSeenAt           pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
}

type ProviderEvent struct {
	ProviderAccountID   string             `db:"provider_account_id" json:"provider_account_id"`
	EventID             string             `db:"event_id" json:"event_id"`
	EventType           string             `db:"event_type" json:"event_type"`
	ObjectID            pgtype.Text        `db:"object_id" json:"object_id"`
	ApiVersion          pgtype.Text        `db:"api_version" json:"api_version"`
	Livemode            bool               `db:"livemode" json:"livemode"`
	Payload             []byte             `db:"payload" json:"payload"`
	ReceivedAt          pgtype.Timestamptz `db:"received_at" json:"received_at"`
	ProcessingStartedAt pgtype.Timestamptz `db:"processing_started_at" json:"processing_started_at"`
	ProcessedAt         pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
	AttemptCount        int32              `db:"attempt_count" json:"attempt_count"`
	LastErrorClass      pgtype.Text        `db:"last_error_class" json:"last_error_class"`
}
