// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package paymentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AttachCanaryOrder(ctx context.Context, arg AttachCanaryOrderParams) error
	ClaimProviderEvent(ctx context.Context) (ProviderEvent, error)
	CompleteCanaryRun(ctx context.Context, arg CompleteCanaryRunParams) (PaymentCanaryRun, error)
	CountCanaryFailures(ctx context.Context, intervalWindow pgtype.Interval) (int64, error)
	CountJournalIncomplete(ctx context.Context) (int64, error)
	CountPendingProviderEvents(ctx context.Context) (int64, error)
	CountStaleOrders(ctx context.Context, olderThan pgtype.Interval) (int64, error)
	CountUnmatchedBalanceTransactions(ctx context.Context) (int64, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (PaymentOrder, error)
	EnsureLedgerAccount(ctx context.Context, arg EnsureLedgerAccountParams) (LedgerAccount, error)
	EnsureLedgerCommand(ctx context.Context, arg EnsureLedgerCommandParams) (LedgerCommand, error)
	GetCanaryRun(ctx context.Context, id string) (PaymentCanaryRun, error)
	GetOrder(ctx context.Context, id string) (PaymentOrder, error)
	GetOrderByBalanceTransaction(ctx context.Context, stripeBalanceTransactionID pgtype.Text) (PaymentOrder, error)
	GetOrderByPaymentIntent(ctx context.Context, stripePaymentIntentID pgtype.Text) (PaymentOrder, error)
	InsertProviderEvent(ctx context.Context, arg InsertProviderEventParams) (ProviderEvent, error)
	LatestCanaryRuns(ctx context.Context) ([]PaymentCanaryRun, error)
	MarkLedgerAccountAccepted(ctx context.Context, registryKey string) error
	MarkLedgerCommandAccepted(ctx context.Context, arg MarkLedgerCommandAcceptedParams) error
	MarkLedgerCommandIntentJournaled(ctx context.Context, commandKey string) error
	MarkLedgerCommandOutcomeJournaled(ctx context.Context, commandKey string) error
	MarkOrderFailed(ctx context.Context, arg MarkOrderFailedParams) (PaymentOrder, error)
	MarkOrderLedgerPosted(ctx context.Context, id string) (PaymentOrder, error)
	MarkOrderProviderPaid(ctx context.Context, arg MarkOrderProviderPaidParams) (PaymentOrder, error)
	MarkProviderEventProcessed(ctx context.Context, arg MarkProviderEventProcessedParams) error
	MarkProviderEventRetryable(ctx context.Context, arg MarkProviderEventRetryableParams) error
	OldestPendingProviderEventAgeSeconds(ctx context.Context) (int64, error)
	SetLedgerCommandPayload(ctx context.Context, arg SetLedgerCommandPayloadParams) error
	SetOrderCheckoutSession(ctx context.Context, arg SetOrderCheckoutSessionParams) (PaymentOrder, error)
	SetOrderPaymentIntent(ctx context.Context, arg SetOrderPaymentIntentParams) (PaymentOrder, error)
	StartCanaryRun(ctx context.Context, arg StartCanaryRunParams) (PaymentCanaryRun, error)
	UpsertBalanceTransaction(ctx context.Context, arg UpsertBalanceTransactionParams) (ProviderBalanceTransaction, error)
}

var _ Querier = (*Queries)(nil)
