apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openbao.guardian.dev_auditdevices.yaml
  - openbao.guardian.dev_authbackends.yaml
  - openbao.guardian.dev_kubernetesauthroles.yaml
  - openbao.guardian.dev_mounts.yaml
  - openbao.guardian.dev_mounttunes.yaml
  - openbao.guardian.dev_pkiroles.yaml
  - openbao.guardian.dev_pkirootissuers.yaml
  - openbao.guardian.dev_policies.yaml
