apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - database-load.yaml
  - database-dr.yaml
  - harbor-oci-read.yaml
  - http-load.yaml
  - openbao-load.yaml
  - storage-smoke.yaml
