apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linstor
  namespace: cozy-linstor
spec:
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: piraeus.io
              version: v1
              kind: LinstorCluster
              name: linstorcluster
            patch: |-
              - op: add
                path: /spec/linstorPassphraseSecret
                value: guardian-linstor-master-passphrase
