apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - flagger-helmrelease.yaml
  - flagger-networkpolicy.yaml
  - alert-provider.yaml
  - metric-templates.yaml
