apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds/openbao.guardian.dev_auditdevices.yaml
  - crds/openbao.guardian.dev_authbackends.yaml
  - crds/openbao.guardian.dev_kubernetesauthroles.yaml
  - crds/openbao.guardian.dev_mounts.yaml
  - crds/openbao.guardian.dev_mounttunes.yaml
  - crds/openbao.guardian.dev_policies.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
