apiVersion: v1
kind: Namespace
metadata:
  name: guardian-analytics
  labels:
    app.kubernetes.io/name: guardian-analytics
    app.kubernetes.io/part-of: guardian
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
