apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ddl-configmap.yaml
  - ddl-job.yaml
  - cockpit-rollup.yaml
  - electric.yaml
  - ingress.yaml
  - networkpolicy.yaml
  - postgres.yaml
