// GENERATED by //src/services/mythrad/sim/client:tablegen — do not edit.
// The numbers are the session crate's (sim/client/session); regenerate
// with `bazelisk run //src/services/mythrad/sim:refresh`.

/**
 * Telemetry codes the session core emits, 1..22. Host-minted codes live in
 * `HostEmit` (ports.ts) and start at 1000 so the two ranges can never be
 * confused.
 */
export const Emit = {
  connectedHelloSent: 1,
  welcome: 2,
  eventApplied: 3,
  rollback: 4,
  resyncRequested: 5,
  snapshotRestored: 6,
  checkSent: 7,
  verdict: 8,
  mismatch: 9,
  reject: 10,
  moduleSwapWanted: 11,
  moduleSwapped: 12,
  clockState: 13,
  intentSent: 14,
  autoRejoin: 15,
  restoreFailed: 16,
  presence: 17,
  replayed: 18,
  eventArrived: 19,
  intentAnswered: 20,
  intentResent: 21,
  intentDropped: 22,
} as const;

export type EmitCode = (typeof Emit)[keyof typeof Emit];

/**
 * Why the core gave up on the state it had. One numbering across both recovery
 * verbs: only `streamOverflow` and `framing` arrive as `Request.teardown`,
 * everything else as `Request.resyncWanted`.
 */
export const ResyncReason = {
  clock: 1,
  lateEvent: 2,
  eventRejected: 3,
  hashMismatch: 4,
  checkAgedOut: 5,
  moduleEpoch: 6,
  terrainFetch: 7,
  restoreFailed: 8,
  queueOverflow: 9,
  moduleSwapped: 10,
  streamOverflow: 11,
  framing: 12,
  replayRefused: 13,
} as const;

export type ResyncReasonCode = (typeof ResyncReason)[keyof typeof ResyncReason];

/**
 * `request(kind, a)` codes the session core raises to the host.
 */
export const Request = {
  needTerrain: 1,
  needModule: 2,
  resyncWanted: 3,
  teardown: 4,
} as const;

export type RequestCode = (typeof Request)[keyof typeof Request];

/**
 * The high half of `Emit.intentDropped`'s `a` slot.
 */
export const IntentDrop = {
  overflow: 1,
  reidentify: 2,
} as const;

export type IntentDropCode = (typeof IntentDrop)[keyof typeof IntentDrop];
