crate = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")
crate.from_cargo(
    name = "directus_migration_monitor_crates",
    cargo_lockfile = "//src/products/directus-migration-monitor:Cargo.lock",
    manifests = ["//src/products/directus-migration-monitor:Cargo.toml"],
)
use_repo(crate, "directus_migration_monitor_crates")
