apiVersion: openbao.guardian.dev/v1alpha1
kind: OpenBaoPKIRole
metadata:
  name: openbao-api
spec:
  mountPath: pki/openbao-api
  roleName: openbao-api
  ttl: 2160h
  maxTTL: 2160h
  allowLocalhost: true
  allowedDomains:
    - guardian-openbao
    - guardian-openbao.tenant-guardian
    - guardian-openbao.tenant-guardian.svc
    - guardian-openbao.tenant-guardian.svc.cozy.local
    - guardian-openbao.tenant-guardian.svc.cluster.local
    - guardian-openbao-active
    - guardian-openbao-active.tenant-guardian
    - guardian-openbao-active.tenant-guardian.svc
    - guardian-openbao-active.tenant-guardian.svc.cozy.local
    - guardian-openbao-active.tenant-guardian.svc.cluster.local
    - guardian-openbao-internal
    - guardian-openbao-internal.tenant-guardian
    - guardian-openbao-internal.tenant-guardian.svc
    - guardian-openbao-internal.tenant-guardian.svc.cozy.local
    - guardian-openbao-internal.tenant-guardian.svc.cluster.local
    - guardian-openbao-0.guardian-openbao-internal
    - guardian-openbao-0.guardian-openbao-internal.tenant-guardian
    - guardian-openbao-0.guardian-openbao-internal.tenant-guardian.svc
    - guardian-openbao-0.guardian-openbao-internal.tenant-guardian.svc.cozy.local
    - guardian-openbao-0.guardian-openbao-internal.tenant-guardian.svc.cluster.local
    - guardian-openbao-1.guardian-openbao-internal
    - guardian-openbao-1.guardian-openbao-internal.tenant-guardian
    - guardian-openbao-1.guardian-openbao-internal.tenant-guardian.svc
    - guardian-openbao-1.guardian-openbao-internal.tenant-guardian.svc.cozy.local
    - guardian-openbao-1.guardian-openbao-internal.tenant-guardian.svc.cluster.local
    - guardian-openbao-2.guardian-openbao-internal
    - guardian-openbao-2.guardian-openbao-internal.tenant-guardian
    - guardian-openbao-2.guardian-openbao-internal.tenant-guardian.svc
    - guardian-openbao-2.guardian-openbao-internal.tenant-guardian.svc.cozy.local
    - guardian-openbao-2.guardian-openbao-internal.tenant-guardian.svc.cluster.local
  allowBareDomains: true
  allowSubdomains: false
  allowGlobDomains: false
  allowWildcardCertificates: false
  allowAnyName: false
  enforceHostnames: true
  allowIPSANs: true
  allowedIPSANsCIDR:
    - 127.0.0.1/32
  serverFlag: true
  clientFlag: false
  codeSigningFlag: false
  emailProtectionFlag: false
  keyType: ec
  keyBits: 256
  keyUsage:
    - DigitalSignature
    - KeyEncipherment
  cnValidations:
    - hostname
  useCSRCommonName: true
  useCSRSANs: true
  generateLease: false
  noStore: false
  requireCN: false
  deletionPolicy: Retain
