apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: postflight-session-seal
  namespace: tenant-guardian-prod
  labels:
    app.kubernetes.io/name: company-site
    app.kubernetes.io/part-of: guardian
spec:
  length: 64
  digits: 8
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postflight-session-seal
  namespace: tenant-guardian-prod
  labels:
    app.kubernetes.io/name: company-site
    app.kubernetes.io/part-of: guardian
spec:
  refreshInterval: "0"
  target:
    name: postflight-session-seal
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: postflight-session-seal
