apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - project.yaml
  - secrets.yaml
  - company-stage-prod.yaml
  - iam-namespace.yaml
  - iam-project.yaml
  - iam-secrets.yaml
  - iam-stage-prod.yaml
  - products-namespace.yaml
  - products-project.yaml
  - products-secrets.yaml
  - products-stage-prod.yaml
  - products-payments-stage-prod.yaml
  - products-postflight-stage-prod.yaml
