apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - project.yaml
  - secrets.yaml
  - stage.yaml
  - iam-namespace.yaml
  - iam-project.yaml
  - iam-secrets.yaml
  - iam-stage-beta.yaml
