apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - products-namespace.yaml
  - products-project.yaml
  - products-secrets.yaml
  - products-postflight-cli-stage-nightly.yaml
