apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: payments-prod
  namespace: guardian-products
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: payments
      sources:
        direct: true
  promotionTemplate:
    spec:
      vars:
        - name: repoURL
          value: https://github.com/guardian-intelligence/guardian.git
        - name: serviceRepo
          value: ghcr.io/guardian-intelligence/payments
        - name: canaryRepo
          value: ghcr.io/guardian-intelligence/payments-canary
      steps:
        - uses: git-clone
          config:
            repoURL: ${{ vars.repoURL }}
            checkout:
              - branch: main
                path: ./repo
        - uses: yaml-update
          config:
            path: ./repo/src/infrastructure/deployments/payments/prod/deployment.yaml
            updates:
              - key: spec.template.spec.containers.0.image
                value: ${{ vars.serviceRepo }}@${{ imageFrom(vars.serviceRepo).Digest }}
        - uses: yaml-update
          config:
            path: ./repo/src/infrastructure/deployments/payments/prod/browser-canary.yaml
            updates:
              - key: spec.jobTemplate.spec.template.spec.containers.0.image
                value: ${{ vars.canaryRepo }}@${{ imageFrom(vars.canaryRepo).Digest }}
        - uses: yaml-update
          config:
            path: ./repo/src/infrastructure/deployments/guardian/system/release-manifest.yaml
            updates:
              - key: releases.payments.prod.image
                value: ${{ vars.serviceRepo }}@${{ imageFrom(vars.serviceRepo).Digest }}
              - key: releases.payments-canary.prod.image
                value: ${{ vars.canaryRepo }}@${{ imageFrom(vars.canaryRepo).Digest }}
        - uses: git-commit
          as: commit
          config:
            path: ./repo
            message: promote payments (prod) to ${{ imageFrom(vars.serviceRepo).Digest }}
        - uses: git-push
          as: push
          config:
            path: ./repo
            generateTargetBranch: true
        - uses: git-open-pr
          as: open-pr
          config:
            repoURL: ${{ vars.repoURL }}
            provider: github
            sourceBranch: ${{ outputs.push.branch }}
            targetBranch: main
            title: promote payments (prod) to ${{ imageFrom(vars.serviceRepo).Digest }}
        - uses: git-wait-for-pr
          if: ${{ status('open-pr') == 'Succeeded' }}
          config:
            repoURL: ${{ vars.repoURL }}
            prNumber: ${{ outputs['open-pr'].pr.id }}
