apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tenant-guardian
resources:
  - authbackends/kubernetes.yaml
  - authroles/external-dns.yaml
  - mounts/kv.yaml
  - policies/external-dns.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: guardian
      guardian.dev/component: secrets
      guardian.dev/tenant-id: gi-guardian
