apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tenant-guardian
resources:
  - authbackends/kubernetes.yaml
  - authroles/cert-manager-openbao-api-issuer.yaml
  - authroles/external-dns.yaml
  - authroles/ops-controller.yaml
  - mounts/kv.yaml
  - mounts/pki-openbao-api.yaml
  - mounttunes/kv.yaml
  - pkiroles/openbao-api.yaml
  - pkirootissuers/openbao-api-root-2026.yaml
  - policies/cert-manager-openbao-api-issuer.yaml
  - policies/external-dns.yaml
  - policies/ops-controller.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: guardian
      guardian.dev/component: secrets
      guardian.dev/tenant-id: gi-guardian
