load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "pgtest",
    testonly = True,
    srcs = ["pgtest.go"],
    importpath = "github.com/guardian-intelligence/guardian/src/postflight/controlplane/pgtest",
    visibility = [
        "//src/chunkies:__subpackages__",
        "//src/services/payments:__pkg__",
        "//src/postflight:__subpackages__",
        "//src/tools/postflight-hammer:__pkg__",
    ],
    deps = ["@com_github_jackc_pgx_v5//:pgx"],
)
