apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tenant-guardian
resources:
  - ../base
images:
  - name: guardian/openbao-ops-controller
    newName: harbor.guardianintelligence.org/guardian/openbao-ops-controller
    digest: sha256:4ce39a4aba17d47b70ab3d28834090b5ebe457f590f11bf2c3c2683c2916b4aa
