apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tenant-guardian
resources:
  - ../base
images:
  - name: guardian/openbao-ops-controller
    newName: harbor.guardianintelligence.org/guardian/openbao-ops-controller
    digest: sha256:bfd7a69106cf2fb9085995463bd9d21443cbb88d0c2f19e1c750b0f71876440b
