apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tenant-guardian
resources:
  - ../base
images:
  - name: guardian/openbao-ops-controller
    newName: ghcr.io/guardian-intelligence/guardian/openbao-ops-controller
    digest: sha256:684eeb25948be49933b7b219d822dcfe7b549b6701a15b01caa6821be39a10a1
