load("@rules_shell//shell:sh_test.bzl", "sh_test")
load("@rules_python//python:defs.bzl", "py_test")

exports_files(["pins.env"])

py_test(
    name = "stdout_test",
    size = "small",
    srcs = ["stdout_test.py"],
    data = [
        "build.sh",
        "build-upstream.sh",
    ],
)

sh_test(
    name = "image_test",
    size = "small",
    srcs = ["image_test.sh"],
    args = [
        "$(rootpath build.sh)",
        "$(rootpath build-upstream.sh)",
        "$(rootpath render-qemu-template.py)",
        "$(rootpath pins.env)",
    ],
    data = [
        "build.sh",
        "build-upstream.sh",
        "pins.env",
        "render-qemu-template.py",
    ],
)
