apiVersion: apps.cozystack.io/v1alpha1
kind: Tenant
metadata:
  name: guardian
  namespace: tenant-root
  labels:
    guardian.dev/tenant-id: gi-guardian
spec:
  etcd: false
  host: ""
  ingress: false
  monitoring: false
  resourceQuotas: {}
  schedulingClass: ""
  seaweedfs: false
