// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package paymentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countStaleOrders = `-- name: CountStaleOrders :one
SELECT count(*)::bigint
FROM payment_orders
WHERE status NOT IN ('ledger_posted', 'failed')
  AND created_at < now() - $1::interval
`

func (q *Queries) CountStaleOrders(ctx context.Context, olderThan pgtype.Interval) (int64, error) {
	row := q.db.QueryRow(ctx, countStaleOrders, olderThan)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO payment_orders (
    id, organization_id, provider, provider_account_id, currency, amount_cents,
    synthetic, status, trace_id
) VALUES (
    $1, $2, 'stripe', $3, $4, $5, true, 'created', $6
)
RETURNING id, organization_id, provider, provider_account_id, currency, amount_cents, synthetic, status, trace_id, stripe_checkout_session_id, stripe_payment_intent_id, stripe_charge_id, stripe_balance_transaction_id, failure_class, created_at, updated_at, paid_at, ledger_posted_at
`

type CreateOrderParams struct {
	ID                string `db:"id" json:"id"`
	OrganizationID    string `db:"organization_id" json:"organization_id"`
	ProviderAccountID string `db:"provider_account_id" json:"provider_account_id"`
	Currency          string `db:"currency" json:"currency"`
	AmountCents       int64  `db:"amount_cents" json:"amount_cents"`
	TraceID           string `db:"trace_id" json:"trace_id"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (PaymentOrder, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.OrganizationID,
		arg.ProviderAccountID,
		arg.Currency,
		arg.AmountCents,
		arg.TraceID,
	)
	var i PaymentOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.Currency,
		&i.AmountCents,
		&i.Synthetic,
		&i.Status,
		&i.TraceID,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.StripeChargeID,
		&i.StripeBalanceTransactionID,
		&i.FailureClass,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.LedgerPostedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, organization_id, provider, provider_account_id, currency, amount_cents, synthetic, status, trace_id, stripe_checkout_session_id, stripe_payment_intent_id, stripe_charge_id, stripe_balance_transaction_id, failure_class, created_at, updated_at, paid_at, ledger_posted_at FROM payment_orders WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id string) (PaymentOrder, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i PaymentOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.Currency,
		&i.AmountCents,
		&i.Synthetic,
		&i.Status,
		&i.TraceID,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.StripeChargeID,
		&i.StripeBalanceTransactionID,
		&i.FailureClass,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.LedgerPostedAt,
	)
	return i, err
}

const getOrderByBalanceTransaction = `-- name: GetOrderByBalanceTransaction :one
SELECT id, organization_id, provider, provider_account_id, currency, amount_cents, synthetic, status, trace_id, stripe_checkout_session_id, stripe_payment_intent_id, stripe_charge_id, stripe_balance_transaction_id, failure_class, created_at, updated_at, paid_at, ledger_posted_at FROM payment_orders WHERE stripe_balance_transaction_id = $1
`

func (q *Queries) GetOrderByBalanceTransaction(ctx context.Context, stripeBalanceTransactionID pgtype.Text) (PaymentOrder, error) {
	row := q.db.QueryRow(ctx, getOrderByBalanceTransaction, stripeBalanceTransactionID)
	var i PaymentOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.Currency,
		&i.AmountCents,
		&i.Synthetic,
		&i.Status,
		&i.TraceID,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.StripeChargeID,
		&i.StripeBalanceTransactionID,
		&i.FailureClass,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.LedgerPostedAt,
	)
	return i, err
}

const getOrderByPaymentIntent = `-- name: GetOrderByPaymentIntent :one
SELECT id, organization_id, provider, provider_account_id, currency, amount_cents, synthetic, status, trace_id, stripe_checkout_session_id, stripe_payment_intent_id, stripe_charge_id, stripe_balance_transaction_id, failure_class, created_at, updated_at, paid_at, ledger_posted_at FROM payment_orders WHERE stripe_payment_intent_id = $1
`

func (q *Queries) GetOrderByPaymentIntent(ctx context.Context, stripePaymentIntentID pgtype.Text) (PaymentOrder, error) {
	row := q.db.QueryRow(ctx, getOrderByPaymentIntent, stripePaymentIntentID)
	var i PaymentOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.Currency,
		&i.AmountCents,
		&i.Synthetic,
		&i.Status,
		&i.TraceID,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.StripeChargeID,
		&i.StripeBalanceTransactionID,
		&i.FailureClass,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.LedgerPostedAt,
	)
	return i, err
}

const markOrderFailed = `-- name: MarkOrderFailed :one
UPDATE payment_orders
SET status = 'failed',
    failure_class = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, organization_id, provider, provider_account_id, currency, amount_cents, synthetic, status, trace_id, stripe_checkout_session_id, stripe_payment_intent_id, stripe_charge_id, stripe_balance_transaction_id, failure_class, created_at, updated_at, paid_at, ledger_posted_at
`

type MarkOrderFailedParams struct {
	ID           string      `db:"id" json:"id"`
	FailureClass pgtype.Text `db:"failure_class" json:"failure_class"`
}

func (q *Queries) MarkOrderFailed(ctx context.Context, arg MarkOrderFailedParams) (PaymentOrder, error) {
	row := q.db.QueryRow(ctx, markOrderFailed, arg.ID, arg.FailureClass)
	var i PaymentOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.Currency,
		&i.AmountCents,
		&i.Synthetic,
		&i.Status,
		&i.TraceID,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.StripeChargeID,
		&i.StripeBalanceTransactionID,
		&i.FailureClass,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.LedgerPostedAt,
	)
	return i, err
}

const markOrderLedgerPosted = `-- name: MarkOrderLedgerPosted :one
UPDATE payment_orders
SET status = 'ledger_posted',
    ledger_posted_at = COALESCE(ledger_posted_at, now()),
    updated_at = now()
WHERE id = $1
RETURNING id, organization_id, provider, provider_account_id, currency, amount_cents, synthetic, status, trace_id, stripe_checkout_session_id, stripe_payment_intent_id, stripe_charge_id, stripe_balance_transaction_id, failure_class, created_at, updated_at, paid_at, ledger_posted_at
`

func (q *Queries) MarkOrderLedgerPosted(ctx context.Context, id string) (PaymentOrder, error) {
	row := q.db.QueryRow(ctx, markOrderLedgerPosted, id)
	var i PaymentOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.Currency,
		&i.AmountCents,
		&i.Synthetic,
		&i.Status,
		&i.TraceID,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.StripeChargeID,
		&i.StripeBalanceTransactionID,
		&i.FailureClass,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.LedgerPostedAt,
	)
	return i, err
}

const markOrderProviderPaid = `-- name: MarkOrderProviderPaid :one
UPDATE payment_orders
SET stripe_payment_intent_id = $2,
    stripe_charge_id = $3,
    stripe_balance_transaction_id = $4,
    status = 'provider_paid',
    paid_at = COALESCE(paid_at, now()),
    updated_at = now()
WHERE id = $1
RETURNING id, organization_id, provider, provider_account_id, currency, amount_cents, synthetic, status, trace_id, stripe_checkout_session_id, stripe_payment_intent_id, stripe_charge_id, stripe_balance_transaction_id, failure_class, created_at, updated_at, paid_at, ledger_posted_at
`

type MarkOrderProviderPaidParams struct {
	ID                         string      `db:"id" json:"id"`
	StripePaymentIntentID      pgtype.Text `db:"stripe_payment_intent_id" json:"stripe_payment_intent_id"`
	StripeChargeID             pgtype.Text `db:"stripe_charge_id" json:"stripe_charge_id"`
	StripeBalanceTransactionID pgtype.Text `db:"stripe_balance_transaction_id" json:"stripe_balance_transaction_id"`
}

func (q *Queries) MarkOrderProviderPaid(ctx context.Context, arg MarkOrderProviderPaidParams) (PaymentOrder, error) {
	row := q.db.QueryRow(ctx, markOrderProviderPaid,
		arg.ID,
		arg.StripePaymentIntentID,
		arg.StripeChargeID,
		arg.StripeBalanceTransactionID,
	)
	var i PaymentOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.Currency,
		&i.AmountCents,
		&i.Synthetic,
		&i.Status,
		&i.TraceID,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.StripeChargeID,
		&i.StripeBalanceTransactionID,
		&i.FailureClass,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.LedgerPostedAt,
	)
	return i, err
}

const setOrderCheckoutSession = `-- name: SetOrderCheckoutSession :one
UPDATE payment_orders
SET stripe_checkout_session_id = $2,
    status = 'checkout_open',
    updated_at = now()
WHERE id = $1
RETURNING id, organization_id, provider, provider_account_id, currency, amount_cents, synthetic, status, trace_id, stripe_checkout_session_id, stripe_payment_intent_id, stripe_charge_id, stripe_balance_transaction_id, failure_class, created_at, updated_at, paid_at, ledger_posted_at
`

type SetOrderCheckoutSessionParams struct {
	ID                      string      `db:"id" json:"id"`
	StripeCheckoutSessionID pgtype.Text `db:"stripe_checkout_session_id" json:"stripe_checkout_session_id"`
}

func (q *Queries) SetOrderCheckoutSession(ctx context.Context, arg SetOrderCheckoutSessionParams) (PaymentOrder, error) {
	row := q.db.QueryRow(ctx, setOrderCheckoutSession, arg.ID, arg.StripeCheckoutSessionID)
	var i PaymentOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.Currency,
		&i.AmountCents,
		&i.Synthetic,
		&i.Status,
		&i.TraceID,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.StripeChargeID,
		&i.StripeBalanceTransactionID,
		&i.FailureClass,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.LedgerPostedAt,
	)
	return i, err
}

const setOrderPaymentIntent = `-- name: SetOrderPaymentIntent :one
UPDATE payment_orders
SET stripe_payment_intent_id = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, organization_id, provider, provider_account_id, currency, amount_cents, synthetic, status, trace_id, stripe_checkout_session_id, stripe_payment_intent_id, stripe_charge_id, stripe_balance_transaction_id, failure_class, created_at, updated_at, paid_at, ledger_posted_at
`

type SetOrderPaymentIntentParams struct {
	ID                    string      `db:"id" json:"id"`
	StripePaymentIntentID pgtype.Text `db:"stripe_payment_intent_id" json:"stripe_payment_intent_id"`
}

func (q *Queries) SetOrderPaymentIntent(ctx context.Context, arg SetOrderPaymentIntentParams) (PaymentOrder, error) {
	row := q.db.QueryRow(ctx, setOrderPaymentIntent, arg.ID, arg.StripePaymentIntentID)
	var i PaymentOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.Currency,
		&i.AmountCents,
		&i.Synthetic,
		&i.Status,
		&i.TraceID,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.StripeChargeID,
		&i.StripeBalanceTransactionID,
		&i.FailureClass,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.LedgerPostedAt,
	)
	return i, err
}
