load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_clippy", "rust_test")

rust_binary(
    name = "pipe-to-remote-box",
    srcs = ["src/main.rs"],
    edition = "2024",
    rustc_env = {"CARGO_PKG_VERSION": "0.1.0-pre"},
    visibility = ["//visibility:public"],
    deps = ["@pipe_to_remote_box_crates//:clap"],
)

rust_test(
    name = "pipe_to_remote_box_test",
    crate = ":pipe-to-remote-box",
    edition = "2024",
)

rust_clippy(
    name = "clippy",
    testonly = True,
    deps = [":pipe-to-remote-box", ":pipe_to_remote_box_test"],
)
