apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - directus.yaml
  - directus-ingress.yaml
  - directus-provisioner.yaml
  - directus-secrets.yaml
  - networkpolicy.yaml
  - postgres.yaml
