apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ddl-configmap.yaml
  - ddl-job.yaml
  - cockpit-rollup.yaml
  - cockpit-events.yaml
  - directus.yaml
  - directus-ingress.yaml
  - directus-provisioner.yaml
  - directus-secrets.yaml
  - electric.yaml
  - ingress.yaml
  - networkpolicy.yaml
  - postgres.yaml
