load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "journaltest",
    testonly = True,
    srcs = ["journaltest.go"],
    importpath = "github.com/guardian-intelligence/guardian/src/chunkies/journal/journaltest",
    visibility = ["//src/chunkies:__subpackages__"],
    deps = ["//src/chunkies/journal"],
)
