apiVersion: apps.cozystack.io/v1alpha1
kind: Tenant
metadata:
  name: secrets
  namespace: tenant-guardian
  labels:
    guardian.dev/tenant-id: gi-secrets
spec:
  etcd: false
  host: ""
  ingress: false
  monitoring: false
  resourceQuotas: {}
  schedulingClass: ""
  seaweedfs: false
