apiVersion: apps.cozystack.io/v1alpha1
kind: Tenant
metadata:
  name: platform
  namespace: tenant-guardiancommercial
  labels:
    app.kubernetes.io/part-of: guardian
    guardian.dev/product: platform
spec:
  host: platform.guardianintelligence.org
  etcd: false
  ingress: false
  monitoring: false
  seaweedfs: false
