apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstorcluster
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: Merge
spec:
  linstorPassphraseSecret: guardian-linstor-master-passphrase
  properties:
    - name: DrbdOptions/Net/max-buffers
      value: "36864"
    - name: DrbdOptions/Net/rcvbuf-size
      value: "10485760"
    - name: DrbdOptions/Net/sndbuf-size
      value: "10485760"
    - name: DrbdOptions/PeerDevice/c-fill-target
      value: "2048"
    - name: DrbdOptions/PeerDevice/c-max-rate
      value: "737280"
    - name: DrbdOptions/PeerDevice/c-min-rate
      value: "245760"
    - name: DrbdOptions/PeerDevice/resync-rate
      value: "245760"
    - name: DrbdOptions/PeerDevice/c-plan-ahead
      value: "10"
