export const DESIGN = {
  orb: {
    // oil in water, lit from behind, seen down a defocused microscope; sampled
    // from the reference micrograph: verdant green with teal-blue bleeding into it
    cream: "#F0E2CC",
    butter: "#DEB249",
    sage: "#6A8E4A",
    teal: "#2F857C",
    rim: "#FFF8E8",
    rimOpacity: 0.5,
    fringe: 0.12,
    size: 44,
  },
  glass: {
    tint: "#FFFFFF",
    tintAlpha: 0,
    refThickness: 20,
    refFactor: 1.4,
    refDistance: 0.05,
    refDispersion: 7,
    refFresnelRange: 30,
    refFresnelHardness: 10,
    refFresnelFactor: 14,
    glareRange: 22,
    glareHardness: 10,
    glareFactor: 55,
    glareConvergence: 62,
    glareOppositeFactor: 45,
    glareAngle: -45,
    blurRadius: 8,
    blurEdge: true,
    roundness: 3,
    mergeRate: 0.005,
    shadowExpand: 25,
    shadowFactor: 15,
    cover: 0.6,
    raise: 1,
    orbLight: 1,
    domBlur: 14,
  },
  ink: {
    tint: "#1A1238",
    swell: 0.6,
    rippleSpeed: 260,
    lifetime: 4,
    gloss: 1,
    voiceAmp: 1.8,
    voiceWavelength: 180,
    voiceSpeed: 24,
    voiceReach: 320,
    voiceEase: 0.7,
  },
} as const;
