// Saved from the studio's "Save as defaults". Hand edits are fine too.
import type { Tuning } from "./tuning-schema.ts";

export const DEFAULT_TUNING = {
  orb: {
    accent: "#6A45D9",
    soft: "#C9B8F7",
    blush: "#E9A3D4",
    size: 52,
    energyIdle: 0.15,
    energyListen: 0.55,
    energyThink: 0.3,
    energySpeak: 1,
    rippleSpeed: 1.1,
    rippleDensity: 7,
    swirl: 0.8,
    drift: 1,
    breatheHz: 0.25,
    gloss: 1,
    matte: 0.85,
    muteDrain: 0.9,
  },
  glass: {
    tint: "#FFFFFF",
    tintAlpha: 0,
    refThickness: 20,
    refFactor: 1.4,
    refDistance: 0.05,
    refDispersion: 7,
    refFresnelRange: 30,
    refFresnelHardness: 20,
    refFresnelFactor: 20,
    glareRange: 30,
    glareHardness: 20,
    glareFactor: 90,
    glareConvergence: 50,
    glareOppositeFactor: 80,
    glareAngle: -45,
    blurRadius: 8,
    blurEdge: true,
    roundness: 3,
    mergeRate: 0.005,
    shadowExpand: 25,
    shadowFactor: 15,
    cover: 0.85,
    domBlur: 14,
  },
  ink: {
    tint: "#1A1238",
    swell: 0.6,
    rippleSpeed: 260,
    lifetime: 4,
    gloss: 1,
  },
} as const satisfies Tuning;
