// Saved from the studio's "Save as defaults". Hand edits are fine too.
import type { Tuning } from "./tuning-schema.ts";

export const DEFAULT_TUNING = {
  orb: {
    green: "#006A4E",
    red: "#F42A41",
    indigo: "#22407F",
    glow: "#FFD9A0",
    greenAmount: 0.1,
    redAmount: -0.1,
    indigoAmount: 0.06,
    size: 44,
    energyIdle: 0.25,
    energyListen: 0.55,
    energyThink: 0.8,
    energySpeak: 0.7,
    rippleSpeed: 0.35,
    swirl: 0.6,
    ease: 0.9,
    smearScale: 1.6,
    warp: 0.9,
    sharpness: 22,
    blur: 0.022,
    bezel: 0.22,
    refIndex: 1.45,
    dispersion: 6,
    glare: 0.6,
    fresnel: 0.5,
    matte: 0.6,
    glowStrength: 0.9,
    glowRadius: 0.75,
    flameWaver: 0.38,
    flameFlicker: 0.6,
    flameRate: 1,
    flameGust: 0.2,
    breatheHz: 0.1,
  },
  glass: {
    tint: "#FFFFFF",
    tintAlpha: 0,
    refThickness: 20,
    refFactor: 1.4,
    refDistance: 0.05,
    refDispersion: 7,
    refFresnelRange: 30,
    refFresnelHardness: 10,
    refFresnelFactor: 14,
    glareRange: 22,
    glareHardness: 10,
    glareFactor: 55,
    glareConvergence: 62,
    glareOppositeFactor: 45,
    glareAngle: -45,
    blurRadius: 8,
    blurEdge: true,
    roundness: 3,
    mergeRate: 0.005,
    shadowExpand: 25,
    shadowFactor: 15,
    cover: 0.6,
    raise: 1,
    orbLight: 1,
    domBlur: 14,
  },
  ink: {
    tapRipples: false,
    tint: "#1A1238",
    swell: 0.6,
    rippleSpeed: 260,
    lifetime: 4,
    gloss: 1,
    voiceAmp: 1.8,
    voiceWavelength: 180,
    voiceSpeed: 24,
    voiceReach: 320,
    voiceEase: 0.7,
  },
} as const satisfies Tuning;
