apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - stage-tenants.yaml
  - openbao-pki.yaml
  - openbao-vault-issuer.yaml
  - openbao-helmrelease.yaml
  - openbao-networkpolicy.yaml
  - openbao-observability.yaml
  - openbao-rbac.yaml
