apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - agent-ops.yaml
  - behavior-configmap.yaml
  - certificate.yaml
  - chunkies.yaml
  - ingress.yaml
  - internal-keys.yaml
  - networkpolicy.yaml
  - observability.yaml
  - web.yaml
configMapGenerator:
  - name: mythra-behavior
    namespace: tenant-guardian-prod
    files:
      - behavior/client.wasm
      - behavior/park.wasm
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/name: mythrad
        app.kubernetes.io/part-of: guardian
        guardian.dev/product: mythra
        guardian.dev/stage: prod
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
