//! Emits `telemetry.gen.ts`: the session crate's numeric vocabularies as
//! TypeScript tables, so no hand-mirrored copy can drift. The output is
//! committed (diff-tested) and refreshed alongside the wasm artifacts.

use chunkies_session as s;

struct Table {
    doc: &'static str,
    name: &'static str,
    rows: &'static [(&'static str, u64)],
    union: &'static str,
}

const TABLES: &[Table] = &[
    Table {
        doc: "Telemetry codes the session core emits, 1..23. Host-minted codes \
              live in `HostEmit` (ports.ts) and start at 1000 so the two ranges \
              can never be confused.",
        name: "Emit",
        union: "EmitCode",
        rows: &[
            ("connectedHelloSent", s::T_CONNECTED as u64),
            ("welcome", s::T_WELCOME as u64),
            ("eventApplied", s::T_EVENT_APPLIED as u64),
            ("rollback", s::T_ROLLBACK as u64),
            ("resyncRequested", s::T_RESYNC_REQUESTED as u64),
            ("snapshotRestored", s::T_SNAPSHOT_RESTORED as u64),
            ("checkSent", s::T_CHECK_SENT as u64),
            ("verdict", s::T_VERDICT as u64),
            ("mismatch", s::T_MISMATCH as u64),
            ("reject", s::T_REJECT as u64),
            ("moduleSwapWanted", s::T_MODULE_SWAP_WANTED as u64),
            ("moduleSwapped", s::T_MODULE_SWAPPED as u64),
            ("clockState", s::T_CLOCK_STATE as u64),
            ("intentSent", s::T_INTENT_SENT as u64),
            ("autoRejoin", s::T_AUTO_REJOIN as u64),
            ("restoreFailed", s::T_RESTORE_FAILED as u64),
            ("presence", s::T_PRESENCE as u64),
            ("replayed", s::T_REPLAYED as u64),
            ("eventArrived", s::T_EVENT_ARRIVED as u64),
            ("intentAnswered", s::T_INTENT_ANSWERED as u64),
            ("intentResent", s::T_INTENT_RESENT as u64),
            ("intentDropped", s::T_INTENT_DROPPED as u64),
            ("rateChanged", s::T_RATE_CHANGED as u64),
        ],
    },
    Table {
        doc: "Why the core gave up on the state it had. One numbering across \
              both recovery verbs: only `streamOverflow` and `framing` arrive \
              as `Request.teardown`, everything else as `Request.resyncWanted`.",
        name: "ResyncReason",
        union: "ResyncReasonCode",
        rows: &[
            ("clock", s::R_CLOCK as u64),
            ("lateEvent", s::R_LATE_EVENT as u64),
            ("eventRejected", s::R_EVENT_REJECTED as u64),
            ("hashMismatch", s::R_HASH_MISMATCH as u64),
            ("checkAgedOut", s::R_CHECK_AGED_OUT as u64),
            ("moduleEpoch", s::R_MODULE_EPOCH as u64),
            ("terrainFetch", s::R_TERRAIN_FETCH as u64),
            ("restoreFailed", s::R_RESTORE_FAILED as u64),
            ("queueOverflow", s::R_QUEUE_OVERFLOW as u64),
            ("moduleSwapped", s::R_MODULE_SWAPPED as u64),
            ("streamOverflow", s::R_STREAM_OVERFLOW as u64),
            ("framing", s::R_FRAMING as u64),
            ("replayRefused", s::R_REPLAY_REFUSED as u64),
        ],
    },
    Table {
        doc: "`request(kind, a)` codes the session core raises to the host.",
        name: "Request",
        union: "RequestCode",
        rows: &[
            ("needTerrain", s::REQ_NEED_TERRAIN as u64),
            ("needModule", s::REQ_NEED_MODULE as u64),
            ("resyncWanted", s::REQ_RESYNC_WANTED as u64),
            ("teardown", s::REQ_TEARDOWN as u64),
        ],
    },
    Table {
        doc: "The high half of `Emit.intentDropped`'s `a` slot.",
        name: "IntentDrop",
        union: "IntentDropCode",
        rows: &[
            ("overflow", s::DROP_OVERFLOW),
            ("reidentify", s::DROP_REIDENTIFY),
        ],
    },
];

fn wrap_doc(out: &mut String, doc: &str) {
    out.push_str("/**\n");
    let mut line = String::from(" *");
    for word in doc.split_whitespace() {
        if line.len() + 1 + word.len() > 80 {
            out.push_str(&line);
            out.push('\n');
            line = String::from(" *");
        }
        line.push(' ');
        line.push_str(word);
    }
    out.push_str(&line);
    out.push_str("\n */\n");
}

fn main() {
    let path = std::env::args().nth(1).expect("usage: tablegen <out-path>");
    let mut out = String::new();
    out.push_str(
        "// GENERATED by //src/chunkies/sim/client:tablegen — do not edit.\n\
         // The numbers are the session crate's (sim/client/session); regenerate\n\
         // with `bazelisk run //src/chunkies/sim:refresh`.\n",
    );
    for t in TABLES {
        out.push('\n');
        wrap_doc(&mut out, t.doc);
        out.push_str(&format!("export const {} = {{\n", t.name));
        for (name, value) in t.rows {
            out.push_str(&format!("  {name}: {value},\n"));
        }
        out.push_str("} as const;\n\n");
        out.push_str(&format!(
            "export type {} = (typeof {})[keyof typeof {}];\n",
            t.union, t.name, t.name
        ));
    }
    std::fs::write(path, out).expect("write telemetry.gen.ts");
}
