/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerselfRouteImport } from './routes/verself'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as LivezRouteImport } from './routes/livez'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as NewsRouteRouteImport } from './routes/news/route'
import { Route as LettersRouteRouteImport } from './routes/letters/route'
import { Route as WorkshopRouteRouteImport } from './routes/_workshop/route'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as LettersIndexRouteImport } from './routes/letters/index'
import { Route as WorkshopIndexRouteImport } from './routes/_workshop/index'
import { Route as OgSlugRouteImport } from './routes/og/$slug'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as LettersSlugRouteImport } from './routes/letters/$slug'
import { Route as WorkshopSolutionsRouteImport } from './routes/_workshop/solutions'
import { Route as WorkshopPressRouteImport } from './routes/_workshop/press'
import { Route as WorkshopContactRouteImport } from './routes/_workshop/contact'
import { Route as WorkshopCompanyRouteImport } from './routes/_workshop/company'
import { Route as WorkshopChangelogRouteImport } from './routes/_workshop/changelog'
import { Route as WorkshopCareersRouteImport } from './routes/_workshop/careers'
import { Route as WorkshopDesignRouteRouteImport } from './routes/_workshop/design/route'
import { Route as WorkshopDesignIndexRouteImport } from './routes/_workshop/design/index'
import { Route as OgLetterSlugRouteImport } from './routes/og/letter/$slug'
import { Route as WorkshopDesignWorkshopRouteImport } from './routes/_workshop/design/workshop'
import { Route as WorkshopDesignNewsroomRouteImport } from './routes/_workshop/design/newsroom'
import { Route as WorkshopDesignLettersRouteImport } from './routes/_workshop/design/letters'
import { Route as ApiOtelV1TracesRouteImport } from './routes/api/otel/v1/traces'

const VerselfRoute = VerselfRouteImport.update({
  id: '/verself',
  path: '/verself',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LivezRoute = LivezRouteImport.update({
  id: '/livez',
  path: '/livez',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRouteRoute = NewsRouteRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersRouteRoute = LettersRouteRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopRouteRoute = WorkshopRouteRouteImport.update({
  id: '/_workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRouteRoute,
} as any)
const LettersIndexRoute = LettersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LettersRouteRoute,
} as any)
const WorkshopIndexRoute = WorkshopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkshopRouteRoute,
} as any)
const OgSlugRoute = OgSlugRouteImport.update({
  id: '/og/$slug',
  path: '/og/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRouteRoute,
} as any)
const LettersSlugRoute = LettersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LettersRouteRoute,
} as any)
const WorkshopSolutionsRoute = WorkshopSolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => WorkshopRouteRoute,
} as any)
const WorkshopPressRoute = WorkshopPressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => WorkshopRouteRoute,
} as any)
const WorkshopContactRoute = WorkshopContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => WorkshopRouteRoute,
} as any)
const WorkshopCompanyRoute = WorkshopCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => WorkshopRouteRoute,
} as any)
const WorkshopChangelogRoute = WorkshopChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => WorkshopRouteRoute,
} as any)
const WorkshopCareersRoute = WorkshopCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => WorkshopRouteRoute,
} as any)
const WorkshopDesignRouteRoute = WorkshopDesignRouteRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => WorkshopRouteRoute,
} as any)
const WorkshopDesignIndexRoute = WorkshopDesignIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkshopDesignRouteRoute,
} as any)
const OgLetterSlugRoute = OgLetterSlugRouteImport.update({
  id: '/og/letter/$slug',
  path: '/og/letter/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopDesignWorkshopRoute = WorkshopDesignWorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => WorkshopDesignRouteRoute,
} as any)
const WorkshopDesignNewsroomRoute = WorkshopDesignNewsroomRouteImport.update({
  id: '/newsroom',
  path: '/newsroom',
  getParentRoute: () => WorkshopDesignRouteRoute,
} as any)
const WorkshopDesignLettersRoute = WorkshopDesignLettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => WorkshopDesignRouteRoute,
} as any)
const ApiOtelV1TracesRoute = ApiOtelV1TracesRouteImport.update({
  id: '/api/otel/v1/traces',
  path: '/api/otel/v1/traces',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkshopIndexRoute
  '/letters': typeof LettersRouteRouteWithChildren
  '/news': typeof NewsRouteRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/livez': typeof LivezRoute
  '/metrics': typeof MetricsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verself': typeof VerselfRoute
  '/design': typeof WorkshopDesignRouteRouteWithChildren
  '/careers': typeof WorkshopCareersRoute
  '/changelog': typeof WorkshopChangelogRoute
  '/company': typeof WorkshopCompanyRoute
  '/contact': typeof WorkshopContactRoute
  '/press': typeof WorkshopPressRoute
  '/solutions': typeof WorkshopSolutionsRoute
  '/letters/$slug': typeof LettersSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/og/$slug': typeof OgSlugRoute
  '/letters/': typeof LettersIndexRoute
  '/news/': typeof NewsIndexRoute
  '/design/letters': typeof WorkshopDesignLettersRoute
  '/design/newsroom': typeof WorkshopDesignNewsroomRoute
  '/design/workshop': typeof WorkshopDesignWorkshopRoute
  '/og/letter/$slug': typeof OgLetterSlugRoute
  '/design/': typeof WorkshopDesignIndexRoute
  '/api/otel/v1/traces': typeof ApiOtelV1TracesRoute
}
export interface FileRoutesByTo {
  '/healthz': typeof HealthzRoute
  '/livez': typeof LivezRoute
  '/metrics': typeof MetricsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verself': typeof VerselfRoute
  '/careers': typeof WorkshopCareersRoute
  '/changelog': typeof WorkshopChangelogRoute
  '/company': typeof WorkshopCompanyRoute
  '/contact': typeof WorkshopContactRoute
  '/press': typeof WorkshopPressRoute
  '/solutions': typeof WorkshopSolutionsRoute
  '/letters/$slug': typeof LettersSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/og/$slug': typeof OgSlugRoute
  '/': typeof WorkshopIndexRoute
  '/letters': typeof LettersIndexRoute
  '/news': typeof NewsIndexRoute
  '/design/letters': typeof WorkshopDesignLettersRoute
  '/design/newsroom': typeof WorkshopDesignNewsroomRoute
  '/design/workshop': typeof WorkshopDesignWorkshopRoute
  '/og/letter/$slug': typeof OgLetterSlugRoute
  '/design': typeof WorkshopDesignIndexRoute
  '/api/otel/v1/traces': typeof ApiOtelV1TracesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_workshop': typeof WorkshopRouteRouteWithChildren
  '/letters': typeof LettersRouteRouteWithChildren
  '/news': typeof NewsRouteRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/livez': typeof LivezRoute
  '/metrics': typeof MetricsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verself': typeof VerselfRoute
  '/_workshop/design': typeof WorkshopDesignRouteRouteWithChildren
  '/_workshop/careers': typeof WorkshopCareersRoute
  '/_workshop/changelog': typeof WorkshopChangelogRoute
  '/_workshop/company': typeof WorkshopCompanyRoute
  '/_workshop/contact': typeof WorkshopContactRoute
  '/_workshop/press': typeof WorkshopPressRoute
  '/_workshop/solutions': typeof WorkshopSolutionsRoute
  '/letters/$slug': typeof LettersSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/og/$slug': typeof OgSlugRoute
  '/_workshop/': typeof WorkshopIndexRoute
  '/letters/': typeof LettersIndexRoute
  '/news/': typeof NewsIndexRoute
  '/_workshop/design/letters': typeof WorkshopDesignLettersRoute
  '/_workshop/design/newsroom': typeof WorkshopDesignNewsroomRoute
  '/_workshop/design/workshop': typeof WorkshopDesignWorkshopRoute
  '/og/letter/$slug': typeof OgLetterSlugRoute
  '/_workshop/design/': typeof WorkshopDesignIndexRoute
  '/api/otel/v1/traces': typeof ApiOtelV1TracesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/letters'
    | '/news'
    | '/healthz'
    | '/livez'
    | '/metrics'
    | '/sitemap.xml'
    | '/verself'
    | '/design'
    | '/careers'
    | '/changelog'
    | '/company'
    | '/contact'
    | '/press'
    | '/solutions'
    | '/letters/$slug'
    | '/news/$slug'
    | '/og/$slug'
    | '/letters/'
    | '/news/'
    | '/design/letters'
    | '/design/newsroom'
    | '/design/workshop'
    | '/og/letter/$slug'
    | '/design/'
    | '/api/otel/v1/traces'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/healthz'
    | '/livez'
    | '/metrics'
    | '/sitemap.xml'
    | '/verself'
    | '/careers'
    | '/changelog'
    | '/company'
    | '/contact'
    | '/press'
    | '/solutions'
    | '/letters/$slug'
    | '/news/$slug'
    | '/og/$slug'
    | '/'
    | '/letters'
    | '/news'
    | '/design/letters'
    | '/design/newsroom'
    | '/design/workshop'
    | '/og/letter/$slug'
    | '/design'
    | '/api/otel/v1/traces'
  id:
    | '__root__'
    | '/_workshop'
    | '/letters'
    | '/news'
    | '/healthz'
    | '/livez'
    | '/metrics'
    | '/sitemap.xml'
    | '/verself'
    | '/_workshop/design'
    | '/_workshop/careers'
    | '/_workshop/changelog'
    | '/_workshop/company'
    | '/_workshop/contact'
    | '/_workshop/press'
    | '/_workshop/solutions'
    | '/letters/$slug'
    | '/news/$slug'
    | '/og/$slug'
    | '/_workshop/'
    | '/letters/'
    | '/news/'
    | '/_workshop/design/letters'
    | '/_workshop/design/newsroom'
    | '/_workshop/design/workshop'
    | '/og/letter/$slug'
    | '/_workshop/design/'
    | '/api/otel/v1/traces'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkshopRouteRoute: typeof WorkshopRouteRouteWithChildren
  LettersRouteRoute: typeof LettersRouteRouteWithChildren
  NewsRouteRoute: typeof NewsRouteRouteWithChildren
  HealthzRoute: typeof HealthzRoute
  LivezRoute: typeof LivezRoute
  MetricsRoute: typeof MetricsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerselfRoute: typeof VerselfRoute
  OgSlugRoute: typeof OgSlugRoute
  OgLetterSlugRoute: typeof OgLetterSlugRoute
  ApiOtelV1TracesRoute: typeof ApiOtelV1TracesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verself': {
      id: '/verself'
      path: '/verself'
      fullPath: '/verself'
      preLoaderRoute: typeof VerselfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livez': {
      id: '/livez'
      path: '/livez'
      fullPath: '/livez'
      preLoaderRoute: typeof LivezRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters': {
      id: '/letters'
      path: '/letters'
      fullPath: '/letters'
      preLoaderRoute: typeof LettersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workshop': {
      id: '/_workshop'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkshopRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRouteRoute
    }
    '/letters/': {
      id: '/letters/'
      path: '/'
      fullPath: '/letters/'
      preLoaderRoute: typeof LettersIndexRouteImport
      parentRoute: typeof LettersRouteRoute
    }
    '/_workshop/': {
      id: '/_workshop/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkshopIndexRouteImport
      parentRoute: typeof WorkshopRouteRoute
    }
    '/og/$slug': {
      id: '/og/$slug'
      path: '/og/$slug'
      fullPath: '/og/$slug'
      preLoaderRoute: typeof OgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRouteRoute
    }
    '/letters/$slug': {
      id: '/letters/$slug'
      path: '/$slug'
      fullPath: '/letters/$slug'
      preLoaderRoute: typeof LettersSlugRouteImport
      parentRoute: typeof LettersRouteRoute
    }
    '/_workshop/solutions': {
      id: '/_workshop/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof WorkshopSolutionsRouteImport
      parentRoute: typeof WorkshopRouteRoute
    }
    '/_workshop/press': {
      id: '/_workshop/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof WorkshopPressRouteImport
      parentRoute: typeof WorkshopRouteRoute
    }
    '/_workshop/contact': {
      id: '/_workshop/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof WorkshopContactRouteImport
      parentRoute: typeof WorkshopRouteRoute
    }
    '/_workshop/company': {
      id: '/_workshop/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof WorkshopCompanyRouteImport
      parentRoute: typeof WorkshopRouteRoute
    }
    '/_workshop/changelog': {
      id: '/_workshop/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof WorkshopChangelogRouteImport
      parentRoute: typeof WorkshopRouteRoute
    }
    '/_workshop/careers': {
      id: '/_workshop/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof WorkshopCareersRouteImport
      parentRoute: typeof WorkshopRouteRoute
    }
    '/_workshop/design': {
      id: '/_workshop/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof WorkshopDesignRouteRouteImport
      parentRoute: typeof WorkshopRouteRoute
    }
    '/_workshop/design/': {
      id: '/_workshop/design/'
      path: '/'
      fullPath: '/design/'
      preLoaderRoute: typeof WorkshopDesignIndexRouteImport
      parentRoute: typeof WorkshopDesignRouteRoute
    }
    '/og/letter/$slug': {
      id: '/og/letter/$slug'
      path: '/og/letter/$slug'
      fullPath: '/og/letter/$slug'
      preLoaderRoute: typeof OgLetterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workshop/design/workshop': {
      id: '/_workshop/design/workshop'
      path: '/workshop'
      fullPath: '/design/workshop'
      preLoaderRoute: typeof WorkshopDesignWorkshopRouteImport
      parentRoute: typeof WorkshopDesignRouteRoute
    }
    '/_workshop/design/newsroom': {
      id: '/_workshop/design/newsroom'
      path: '/newsroom'
      fullPath: '/design/newsroom'
      preLoaderRoute: typeof WorkshopDesignNewsroomRouteImport
      parentRoute: typeof WorkshopDesignRouteRoute
    }
    '/_workshop/design/letters': {
      id: '/_workshop/design/letters'
      path: '/letters'
      fullPath: '/design/letters'
      preLoaderRoute: typeof WorkshopDesignLettersRouteImport
      parentRoute: typeof WorkshopDesignRouteRoute
    }
    '/api/otel/v1/traces': {
      id: '/api/otel/v1/traces'
      path: '/api/otel/v1/traces'
      fullPath: '/api/otel/v1/traces'
      preLoaderRoute: typeof ApiOtelV1TracesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WorkshopDesignRouteRouteChildren {
  WorkshopDesignLettersRoute: typeof WorkshopDesignLettersRoute
  WorkshopDesignNewsroomRoute: typeof WorkshopDesignNewsroomRoute
  WorkshopDesignWorkshopRoute: typeof WorkshopDesignWorkshopRoute
  WorkshopDesignIndexRoute: typeof WorkshopDesignIndexRoute
}

const WorkshopDesignRouteRouteChildren: WorkshopDesignRouteRouteChildren = {
  WorkshopDesignLettersRoute: WorkshopDesignLettersRoute,
  WorkshopDesignNewsroomRoute: WorkshopDesignNewsroomRoute,
  WorkshopDesignWorkshopRoute: WorkshopDesignWorkshopRoute,
  WorkshopDesignIndexRoute: WorkshopDesignIndexRoute,
}

const WorkshopDesignRouteRouteWithChildren =
  WorkshopDesignRouteRoute._addFileChildren(WorkshopDesignRouteRouteChildren)

interface WorkshopRouteRouteChildren {
  WorkshopDesignRouteRoute: typeof WorkshopDesignRouteRouteWithChildren
  WorkshopCareersRoute: typeof WorkshopCareersRoute
  WorkshopChangelogRoute: typeof WorkshopChangelogRoute
  WorkshopCompanyRoute: typeof WorkshopCompanyRoute
  WorkshopContactRoute: typeof WorkshopContactRoute
  WorkshopPressRoute: typeof WorkshopPressRoute
  WorkshopSolutionsRoute: typeof WorkshopSolutionsRoute
  WorkshopIndexRoute: typeof WorkshopIndexRoute
}

const WorkshopRouteRouteChildren: WorkshopRouteRouteChildren = {
  WorkshopDesignRouteRoute: WorkshopDesignRouteRouteWithChildren,
  WorkshopCareersRoute: WorkshopCareersRoute,
  WorkshopChangelogRoute: WorkshopChangelogRoute,
  WorkshopCompanyRoute: WorkshopCompanyRoute,
  WorkshopContactRoute: WorkshopContactRoute,
  WorkshopPressRoute: WorkshopPressRoute,
  WorkshopSolutionsRoute: WorkshopSolutionsRoute,
  WorkshopIndexRoute: WorkshopIndexRoute,
}

const WorkshopRouteRouteWithChildren = WorkshopRouteRoute._addFileChildren(
  WorkshopRouteRouteChildren,
)

interface LettersRouteRouteChildren {
  LettersSlugRoute: typeof LettersSlugRoute
  LettersIndexRoute: typeof LettersIndexRoute
}

const LettersRouteRouteChildren: LettersRouteRouteChildren = {
  LettersSlugRoute: LettersSlugRoute,
  LettersIndexRoute: LettersIndexRoute,
}

const LettersRouteRouteWithChildren = LettersRouteRoute._addFileChildren(
  LettersRouteRouteChildren,
)

interface NewsRouteRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteRouteChildren: NewsRouteRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteRouteWithChildren = NewsRouteRoute._addFileChildren(
  NewsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WorkshopRouteRoute: WorkshopRouteRouteWithChildren,
  LettersRouteRoute: LettersRouteRouteWithChildren,
  NewsRouteRoute: NewsRouteRouteWithChildren,
  HealthzRoute: HealthzRoute,
  LivezRoute: LivezRoute,
  MetricsRoute: MetricsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerselfRoute: VerselfRoute,
  OgSlugRoute: OgSlugRoute,
  OgLetterSlugRoute: OgLetterSlugRoute,
  ApiOtelV1TracesRoute: ApiOtelV1TracesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
